// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

library Errors {
    error TokensCannotBeSame();
    error NoReportToDispute();
    error EthTransferFailed();
    error InvalidAmount1();
    error InvalidAmount2();
    error InvalidStateHash();
    error InvalidGasLimit();
    error SettleTooEarly();
    error AlreadySettled();
    error SettleVsDisputeDelayTiming();
    error MsgValueTooLow();
    error FeesTooHigh();
    error MultiplierTooLow();
    error AddressCannotBeZero();
    error InvalidTokenToSwap();
    error NoReportYet();
    error EscalationHalted();
    error AmountsCannotBeZero();
    error DisputeTooLate();
    error DisputeTooEarly();
    error InvalidMode();
    error InvalidTiming();
    error Permit2AmountMismatch();
    error InsufficientInternalBalance();
    error InsufficientInternalAllowance();
    error NeitherTokenIsETH();
    error InvalidMsgValue();
    error TimestampsMustBeZero();
    error NumReportsMustBeZero();
    error InvalidToken();
    error NonZeroAllowance();
    error ZeroAmount();
    error InvalidExpiration();
    error InvalidFulfillFee();
    error InvalidSlippage();
    error InvalidOracleParams();
    error InvalidFulfillFeeParams();
    error MinOutInconsistent();
    error WrongHash();
    error WrongOracleHash();
    error NotActive();
    error Expired();
    error NotSwapper();
    error NotMatched();
    error CantBailOutYet();
    error NothingToWithdraw();
    error OracleSettlementNotEligible();
    error MustBeZero();
}
