// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "./BaseGGTest.sol";
import {CompatTypes} from "./CompatTypes.sol";

// Coverage for FLAG_STORE_PRICE and FLAG_STORE_ALL — the optional opt-in
// composability flags that persist final price / final game state on settle.
contract OpenOracleGGStorageFlagsTest is BaseGGTest {
    uint256 internal constant PRICE_PRECISION = 1e30;

    function setUp() public override {
        BaseGGTest.setUp();
    }

    // Helper: alice reports with given flags, then settles.
    function _runLifecycleWithFlags(uint8 flags)
        internal
        returns (ReportContext memory ctx, uint256 expectedPrice)
    {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = flags;

        vm.prank(alice);
        ctx = _report(p, 1e18, 2000e18, alice, false, false);

        vm.warp(block.timestamp + 301);

        vm.prank(charlie);
        ctx = _settle(ctx);

        expectedPrice = (uint256(1e18) * PRICE_PRECISION) / 2000e18;
    }

    // Use the autogenerated public-mapping getter for finalizedGame.
    // OracleGame has 20 fields, so the getter returns a 20-tuple. Destructure
    // with commas, naming only the fields we want.
    //
    // Field order (must match struct declaration in OpenOracleSlim.sol):
    //   0: currentAmount1   1: currentAmount2     2: currentReporter
    //   3: reportTimestamp  4: settlementTimestamp 5: token1
    //   6: lastReportOppoTime 7: settlementTime   8: escalationHalt
    //   9: protocolFeeRecipient 10: settlerReward 11: token2
    //  12: numReports       13: disputeDelay      14: feePercentage
    //  15: multiplier       16: callbackContract  17: callbackGasLimit
    //  18: protocolFee      19: flags

    function _finalizedSettlementTimestamp(uint256 reportId) internal view returns (uint48 ts) {
        // settlementTimestamp at index 4: 4 leading commas, named, 15 trailing.
        (,,,, ts,,,,,,,,,,,,,,,) = oracle.finalizedGame(reportId);
    }

    function _finalizedToken1(uint256 reportId) internal view returns (address t1) {
        // token1 at index 5: 5 leading commas, named, 14 trailing.
        (,,,,, t1,,,,,,,,,,,,,,) = oracle.finalizedGame(reportId);
    }

    // -------------------------------------------------------------------------
    // No flags: neither finalPrice nor finalizedGame populated
    // -------------------------------------------------------------------------
    function testSettle_NoFlags_NothingStored() public {
        (ReportContext memory ctx,) = _runLifecycleWithFlags(FLAG_TIME_TYPE);
        assertEq(oracle.finalPrice(ctx.reportId), 0, "finalPrice not stored");
        assertEq(uint256(_finalizedSettlementTimestamp(ctx.reportId)), 0, "finalizedGame not stored");
    }

    // -------------------------------------------------------------------------
    // FLAG_STORE_PRICE only
    // -------------------------------------------------------------------------
    function testSettle_StorePriceOnly() public {
        (ReportContext memory ctx, uint256 expectedPrice) =
            _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_PRICE);

        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice stored");
        // finalizedGame not stored (settlementTimestamp == 0).
        assertEq(uint256(_finalizedSettlementTimestamp(ctx.reportId)), 0, "finalizedGame not stored");
    }

    // -------------------------------------------------------------------------
    // FLAG_STORE_ALL only
    // -------------------------------------------------------------------------
    function testSettle_StoreAllOnly() public {
        (ReportContext memory ctx,) = _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_ALL);

        // finalPrice NOT stored.
        assertEq(oracle.finalPrice(ctx.reportId), 0, "finalPrice not stored");

        // finalizedGame stored: settlementTimestamp non-zero, token1 matches.
        assertEq(
            uint256(_finalizedSettlementTimestamp(ctx.reportId)),
            block.timestamp,
            "finalizedGame settlementTimestamp stored"
        );
        assertEq(_finalizedToken1(ctx.reportId), address(token1), "finalizedGame token1 matches");
    }

    // -------------------------------------------------------------------------
    // Both flags: both stored
    // -------------------------------------------------------------------------
    function testSettle_BothFlags() public {
        (ReportContext memory ctx, uint256 expectedPrice) =
            _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_PRICE | FLAG_STORE_ALL);

        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice stored");
        assertEq(
            uint256(_finalizedSettlementTimestamp(ctx.reportId)),
            block.timestamp,
            "finalizedGame stored"
        );
        assertEq(_finalizedToken1(ctx.reportId), address(token1), "finalizedGame token1 matches");
    }

    // -------------------------------------------------------------------------
    // Flags survive a dispute: dispute changes currentAmount1/2, so the settled
    // ratio reflects the dispute outcome (not the initial report).
    // -------------------------------------------------------------------------
    function testSettle_StorePriceAfterDispute_ReflectsDisputedAmounts() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_PRICE;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);

        vm.warp(block.timestamp + 6);
        vm.prank(bob);
        ctx = _dispute(ctx, address(token1), 1.1e18, 2100e18, false, false);

        vm.warp(block.timestamp + 301);
        vm.prank(charlie);
        ctx = _settle(ctx);

        uint256 expectedPrice = (uint256(1.1e18) * PRICE_PRECISION) / 2100e18;
        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice reflects dispute");
    }
}
