// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import "./BaseGGTest.sol";
import {CompatTypes} from "./CompatTypes.sol";

// Coverage for FLAG_STORE_PRICE and FLAG_STORE_ALL — the optional opt-in
// composability flags that persist final price / game state.
contract OpenOracleGGStorageFlagsTest is BaseGGTest {
    uint256 internal constant PRICE_PRECISION = 1e30;

    function setUp() public override {
        BaseGGTest.setUp();
    }

    // Helper: alice reports with given flags, then settles.
    function _runLifecycleWithFlags(uint8 flags)
        internal
        returns (ReportContext memory ctx, uint256 expectedPrice)
    {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = flags;

        vm.prank(alice);
        ctx = _report(p, 1e18, 2000e18, alice, false, false);

        vm.warp(block.timestamp + 301);

        vm.prank(charlie);
        ctx = _settle(ctx);

        expectedPrice = (uint256(1e18) * PRICE_PRECISION) / 2000e18;
    }

    // Use the autogenerated public-mapping getter for storedGame.
    // OracleGame has 20 fields, so the getter returns a 20-tuple. Destructure
    // with commas, naming only the fields we want.
    //
    // Field order (must match struct declaration in OpenOracleSlim.sol):
    //   0: currentAmount1   1: currentAmount2     2: currentReporter
    //   3: reportTimestamp  4: settlementTimestamp 5: token1
    //   6: lastReportOppoTime 7: settlementTime   8: escalationHalt
    //   9: protocolFeeRecipient 10: settlerReward 11: token2
    //  12: numReports       13: disputeDelay      14: feePercentage
    //  15: multiplier       16: callbackContract  17: callbackGasLimit
    //  18: protocolFee      19: flags

    function _finalizedSettlementTimestamp(uint256 reportId) internal view returns (uint48 ts) {
        // settlementTimestamp at index 4: 4 leading commas, named, 15 trailing.
        (,,,, ts,,,,,,,,,,,,,,,) = oracle.storedGame(reportId);
    }

    function _finalizedToken1(uint256 reportId) internal view returns (address t1) {
        // token1 at index 5: 5 leading commas, named, 14 trailing.
        (,,,,, t1,,,,,,,,,,,,,,) = oracle.storedGame(reportId);
    }

    function _storedGameStruct(uint256 reportId) internal view returns (Slim.OracleGame memory g) {
        (bool ok, bytes memory data) = address(oracle).staticcall(abi.encodeWithSignature("storedGame(uint256)", reportId));
        assertTrue(ok, "storedGame getter failed");
        g = abi.decode(data, (Slim.OracleGame));
    }

    function _storedHelperAsPreimage(uint256 reportId) internal view returns (Slim.PreimageHelper memory h) {
        (address creator, uint48 blockTimestamp, uint48 blockNumber) = oracle.storedHelper(reportId);
        h.reportId = reportId;
        h.creator = creator;
        h.blockTimestamp = uint256(blockTimestamp);
        h.blockNumber = uint256(blockNumber);
    }

    function _assertStoredGameMatchesContext(ReportContext memory ctx, string memory label) internal view {
        Slim.OracleGame memory stored = _storedGameStruct(ctx.reportId);
        assertEq(_hashOracle(stored, ctx.helper), oracle.oracleGame(ctx.reportId), label);
        assertEq(stored.currentAmount1, ctx.game.currentAmount1, "stored amount1");
        assertEq(stored.currentAmount2, ctx.game.currentAmount2, "stored amount2");
        assertEq(stored.currentReporter, ctx.game.currentReporter, "stored reporter");
        assertEq(stored.reportTimestamp, ctx.game.reportTimestamp, "stored report timestamp");
        assertEq(stored.settlementTimestamp, ctx.game.settlementTimestamp, "stored settlement timestamp");
        assertEq(stored.lastReportOppoTime, ctx.game.lastReportOppoTime, "stored opposite time");
        assertEq(stored.numReports, ctx.game.numReports, "stored report count");
    }

    function _assertStoredHelperMatchesContext(ReportContext memory ctx) internal view {
        (address creator, uint48 blockTimestamp, uint48 blockNumber) = oracle.storedHelper(ctx.reportId);
        assertEq(creator, ctx.helper.creator, "stored helper creator");
        assertEq(uint256(blockTimestamp), ctx.helper.blockTimestamp, "stored helper timestamp");
        assertEq(uint256(blockNumber), ctx.helper.blockNumber, "stored helper block");
    }

    // -------------------------------------------------------------------------
    // No flags: neither finalPrice nor storedGame populated
    // -------------------------------------------------------------------------
    function testSettle_NoFlags_NothingStored() public {
        (ReportContext memory ctx,) = _runLifecycleWithFlags(FLAG_TIME_TYPE);
        assertEq(oracle.finalPrice(ctx.reportId), 0, "finalPrice not stored");
        assertEq(uint256(_finalizedSettlementTimestamp(ctx.reportId)), 0, "storedGame not stored");
    }

    // -------------------------------------------------------------------------
    // FLAG_STORE_PRICE only
    // -------------------------------------------------------------------------
    function testSettle_StorePriceOnly() public {
        (ReportContext memory ctx, uint256 expectedPrice) =
            _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_PRICE);

        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice stored");
        // storedGame not stored (settlementTimestamp == 0).
        assertEq(uint256(_finalizedSettlementTimestamp(ctx.reportId)), 0, "storedGame not stored");
    }

    // -------------------------------------------------------------------------
    // FLAG_STORE_ALL only
    // -------------------------------------------------------------------------
    function testSettle_StoreAllOnly() public {
        (ReportContext memory ctx,) = _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_ALL);

        // finalPrice NOT stored.
        assertEq(oracle.finalPrice(ctx.reportId), 0, "finalPrice not stored");

        // storedGame stored: settlementTimestamp non-zero, token1 matches.
        assertEq(
            uint256(_finalizedSettlementTimestamp(ctx.reportId)),
            block.timestamp,
            "storedGame settlementTimestamp stored"
        );
        assertEq(_finalizedToken1(ctx.reportId), address(token1), "storedGame token1 matches");
    }

    // -------------------------------------------------------------------------
    // Both flags: both stored
    // -------------------------------------------------------------------------
    function testSettle_BothFlags() public {
        (ReportContext memory ctx, uint256 expectedPrice) =
            _runLifecycleWithFlags(FLAG_TIME_TYPE | FLAG_STORE_PRICE | FLAG_STORE_ALL);

        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice stored");
        assertEq(
            uint256(_finalizedSettlementTimestamp(ctx.reportId)),
            block.timestamp,
            "storedGame stored"
        );
        assertEq(_finalizedToken1(ctx.reportId), address(token1), "storedGame token1 matches");
    }

    // -------------------------------------------------------------------------
    // Flags survive a dispute: dispute changes currentAmount1/2, so the settled
    // ratio reflects the dispute outcome (not the initial report).
    // -------------------------------------------------------------------------
    function testSettle_StorePriceAfterDispute_ReflectsDisputedAmounts() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_PRICE;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);

        vm.warp(block.timestamp + 6);
        vm.prank(bob);
        ctx = _dispute(ctx, address(token1), 1.1e18, 2100e18, false, false);

        vm.warp(block.timestamp + 301);
        vm.prank(charlie);
        ctx = _settle(ctx);

        uint256 expectedPrice = (uint256(1.1e18) * PRICE_PRECISION) / 2100e18;
        assertEq(oracle.finalPrice(ctx.reportId), expectedPrice, "finalPrice reflects dispute");
    }

    function testStoreAll_StoresGameAndHelperOnReport() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_ALL;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);

        _assertStoredGameMatchesContext(ctx, "stored report preimage reconstructs");
        _assertStoredHelperMatchesContext(ctx);
        assertEq(uint256(_storedGameStruct(ctx.reportId).settlementTimestamp), 0, "report not settled");
    }

    function testStoreAll_UpdatesStoredGameAfterDisputeBeforeSettle() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_ALL;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);

        vm.warp(block.timestamp + 6);
        vm.prank(bob);
        ctx = _dispute(ctx, address(token1), 1.1e18, 2100e18, false, false);

        _assertStoredGameMatchesContext(ctx, "stored dispute preimage reconstructs");
        _assertStoredHelperMatchesContext(ctx);
        assertEq(uint256(_storedGameStruct(ctx.reportId).settlementTimestamp), 0, "disputed report not settled");
    }

    function testStoreAll_ReconstructsSettlePreimageFromStoredGameAndHelper() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_ALL;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);

        Slim.OracleGame memory stored = _storedGameStruct(ctx.reportId);
        Slim.PreimageHelper memory helper = _storedHelperAsPreimage(ctx.reportId);

        assertEq(_hashOracle(stored, helper), oracle.oracleGame(ctx.reportId), "stored preimage reconstructs");

        vm.warp(block.timestamp + 301);
        vm.prank(charlie);
        oracle.settle(ctx.reportId, stored, helper);

        stored.settlementTimestamp = uint48(block.timestamp);
        assertEq(oracle.oracleGame(ctx.reportId), _hashOracle(stored, helper), "settled stored preimage reconstructs");
        assertEq(uint256(_storedGameStruct(ctx.reportId).settlementTimestamp), block.timestamp, "stored settlement ts");
    }

    function testNoStoreAll_DoesNotStoreHelper() public {
        vm.prank(alice);
        ReportContext memory ctx = _report(_defaultParams(), 1e18, 2000e18, alice, false, false);

        (address creator, uint48 blockTimestamp, uint48 blockNumber) = oracle.storedHelper(ctx.reportId);
        assertEq(creator, address(0), "helper creator not stored");
        assertEq(uint256(blockTimestamp), 0, "helper timestamp not stored");
        assertEq(uint256(blockNumber), 0, "helper block not stored");
        assertEq(_storedGameStruct(ctx.reportId).currentAmount1, 0, "game not stored");
    }

    function testStoreAll_HelperRemainsUnchangedAcrossDisputeAndSettle() public {
        CompatTypes.CreateReportParams memory p = _defaultParams();
        p.flags = FLAG_TIME_TYPE | FLAG_STORE_ALL;

        vm.prank(alice);
        ReportContext memory ctx = _report(p, 1e18, 2000e18, alice, false, false);
        Slim.PreimageHelper memory storedAtReport = _storedHelperAsPreimage(ctx.reportId);

        vm.warp(block.timestamp + 6);
        vm.prank(bob);
        ctx = _dispute(ctx, address(token1), 1.1e18, 2100e18, false, false);
        assertEq(
            keccak256(abi.encode(_storedHelperAsPreimage(ctx.reportId))),
            keccak256(abi.encode(storedAtReport)),
            "helper unchanged after dispute"
        );

        vm.warp(block.timestamp + 301);
        vm.prank(charlie);
        ctx = _settle(ctx);
        assertEq(
            keccak256(abi.encode(_storedHelperAsPreimage(ctx.reportId))),
            keccak256(abi.encode(storedAtReport)),
            "helper unchanged after settle"
        );
    }
}
